### ISSUE TITLE
Address issue with tests related to ExactMatch and re-enable them

### ISSUE THREAD

**Issue by gab-arrobo** [omec-project/bess#28]
In PR #10, to enable several GitHub Actions, a few tests were temporarily disabled. That is four files were changed of extension to txt. The tests that were disabled are:

- [x] bessctl/module_tests/exact_match.py: #45 addresses this issue
- [x] bessctl/module_tests/placement_constraint.py: #49 addresses this issue
- [x] bessctl/module_tests/wildcard_match.py: #45 addresses this issue
- [x] pybess/test_bess.py: #49 addresses this issue
- [x] 6/7 tests were commented out in core/utils/exact_match_table_test.cc: #56 addresses this issue

This needs to be addressed by properly updating the tests based on the changes made to the ExactMatch class
